### ISSUE TITLE
async example

### ISSUE THREAD

**Issue by corporatepiyush** [developit/preact-cycle#4]
Happen to stop by this page when searching for alternative to React + Redux.
This library seems to be really succinct.

Can someone please add an example of async Ajax/Promise call and how to mutate state after success or error in project readme file ?

**Comment by corporatepiyush** [comment]
can it handle updating the state and render process async or not ?

**Comment by developit** [comment]
Hi @corporatepiyush! Sorry for the delay.

Here's an example of preact-cycle that asynchronously fetches data and persists it back to centralized state using `mutate()`: 
http://jsfiddle.net/developit/1z5f5d5t/

As you can see, this is somewhat similar to how redux-thunk works (actions that are given a `dispatch()` method).

Closing for now since I think this answers your question, but feel free to ask about anything that doesn't seem intuitive!

**Comment by corporatepiyush** [comment]
ah i see. you are passing "mutate" as argument from component to action methods.
Thanks for your reply
